version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - database:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     container_name: wordpress_db

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /var/www/public/:/var/www/html/
     restart: always
     environment:
       VIRTUAL_HOST: ".derhut.com.br,.portal25.com"
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     container_name: wordpress

volumes:
    database:

networks:
    default:
      external:
        name: efforia
